import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import {
  Activity, AlertCircle, Bell, Building2, CalendarDays, Check, CheckCircle2, ChevronRight,
  CircleUserRound, Clock3, Download, FileClock, FileText, Gauge, History, LayoutDashboard,
  LogOut, Menu, MoreHorizontal, Palmtree, Pencil, Plus, Search, Settings2, ShieldCheck,
  Timer, UserCog, Users, X, XCircle,
} from "lucide-react";
import { createContext, useContext, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { toast } from "sonner";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { attendance, auditItems, employees, leaveRequests, roleLabels, team, type Role, type Status } from "@/lib/dha-data";
import { cn } from "@/lib/utils";

type AppContextValue = { role: Role; setRole: (role: Role) => void; checkedIn: boolean; checkedOut: boolean; checkIn: () => void; checkOut: () => void };
const AppContext = createContext<AppContextValue | undefined>(undefined);

export function DHAProvider({ children }: { children: ReactNode }) {
  const [role, setRole] = useState<Role>("hr_admin");
  const [checkedIn, setCheckedIn] = useState(false);
  const [checkedOut, setCheckedOut] = useState(false);
  const value = useMemo(() => ({
    role, setRole, checkedIn, checkedOut,
    checkIn: () => { setCheckedIn(true); toast.success("Checked in at 08:57 AM", { description: "Status: Present · General Shift" }); },
    checkOut: () => { setCheckedOut(true); toast.success("Checked out for today", { description: "Worked time recorded temporarily." }); },
  }), [role, checkedIn, checkedOut]);
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

function useDHA() {
  const context = useContext(AppContext);
  if (!context) throw new Error("DHAProvider is missing");
  return context;
}

const navItems = [
  { label: "Dashboard", to: "/dashboard", icon: LayoutDashboard, roles: ["employee", "manager", "hr_admin", "system_admin"] },
  { label: "My Attendance", to: "/attendance", icon: CalendarDays, roles: ["employee", "manager", "hr_admin", "system_admin"] },
  { label: "Leave", to: "/leave", icon: Palmtree, roles: ["employee", "manager", "hr_admin", "system_admin"] },
  { label: "Team Attendance", to: "/team-attendance", icon: Users, roles: ["manager", "hr_admin", "system_admin"] },
  { label: "Approvals", to: "/approvals", icon: CheckCircle2, roles: ["manager", "hr_admin", "system_admin"] },
  { label: "Employees", to: "/employees", icon: CircleUserRound, roles: ["hr_admin", "system_admin"] },
  { label: "Departments & Shifts", to: "/organization", icon: Building2, roles: ["hr_admin", "system_admin"] },
  { label: "Leave & Holidays", to: "/leave-holidays", icon: CalendarDays, roles: ["hr_admin", "system_admin"] },
  { label: "Reports", to: "/reports", icon: FileText, roles: ["manager", "hr_admin", "system_admin"] },
  { label: "Users & Roles", to: "/users", icon: UserCog, roles: ["system_admin"] },
  { label: "Audit Log", to: "/audit-log", icon: History, roles: ["hr_admin", "system_admin"] },
] as const;

function Brand({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-md bg-primary font-extrabold text-primary-foreground">D</div>{!compact && <div><p className="font-extrabold text-sidebar-foreground">DHA Attendance</p><p className="text-xs text-sidebar-foreground/60">People Operations</p></div>}</div>;
}

function SidebarNav({ onNavigate }: { onNavigate?: () => void }) {
  const { role } = useDHA();
  const path = useRouterState({ select: (s) => s.location.pathname });
  const visible = navItems.filter((item) => item.roles.includes(role as never));
  return <nav className="mt-8 space-y-1">{visible.map((item) => {
    const active = path === item.to;
    return <Link key={item.to} to={item.to} onClick={onNavigate} className={cn("flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-semibold transition-colors", active ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-sidebar-foreground/70 hover:bg-sidebar-accent/60 hover:text-sidebar-foreground")}><item.icon className="size-[18px] shrink-0" /><span>{item.label}</span>{item.label === "Approvals" && <span className="ml-auto rounded-full bg-warning px-2 py-0.5 text-[10px] text-foreground">4</span>}</Link>;
  })}</nav>;
}

function MobileDrawer() {
  const [open, setOpen] = useState(false);
  return <Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open menu"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-72 border-sidebar-border bg-sidebar p-5"><Brand /><SidebarNav onNavigate={() => setOpen(false)} /></SheetContent></Sheet>;
}

function AppShell({ title, eyebrow, children, actions }: { title: string; eyebrow?: string; children: ReactNode; actions?: ReactNode }) {
  const { role, setRole } = useDHA();
  return <div className="min-h-screen bg-background">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-sidebar-border bg-sidebar p-5 lg:block"><Brand /><SidebarNav /><div className="absolute inset-x-5 bottom-5 border-t border-sidebar-border pt-4"><Link to="/profile" className="flex items-center gap-3 rounded-md p-2 text-sidebar-foreground hover:bg-sidebar-accent"><div className="grid size-9 place-items-center rounded-full bg-sidebar-primary text-sm font-bold text-sidebar-primary-foreground">HK</div><div className="min-w-0"><p className="truncate text-sm font-bold">Hamza Khan</p><p className="truncate text-xs text-sidebar-foreground/60">{roleLabels[role]}</p></div></Link></div></aside>
    <div className="lg:pl-64">
      <header className="sticky top-0 z-30 grid h-16 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b bg-card/95 px-4 backdrop-blur md:px-7"><MobileDrawer /><div className="min-w-0"><p className="truncate text-xs font-bold uppercase text-primary">{eyebrow ?? "DHA Company"}</p><h1 className="truncate text-lg font-extrabold md:text-xl">{title}</h1></div><div className="flex shrink-0 items-center gap-2"><select aria-label="Preview role" value={role} onChange={(e) => { setRole(e.target.value as Role); toast.info(`Switched to ${roleLabels[e.target.value as Role]} preview`); }} className="hidden h-9 rounded-md border bg-background px-2 text-xs font-semibold sm:block">{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button asChild variant="ghost" size="icon"><Link to="/notifications" aria-label="Notifications" className="relative"><Bell /><span className="absolute right-1 top-1 size-2 rounded-full bg-destructive" /></Link></Button></div></header>
      <main className="mx-auto max-w-[1500px] p-4 pb-24 md:p-7 lg:pb-8"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-muted-foreground">Tuesday, 29 September 2026 · PKT</p></div>{actions}</div>{children}</main>
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t bg-card px-1 py-1 lg:hidden">{[
      { label: "Home", to: "/dashboard", icon: Gauge }, { label: "Attendance", to: "/attendance", icon: Clock3 }, { label: "Leave", to: "/leave", icon: Palmtree }, { label: "Alerts", to: "/notifications", icon: Bell }, { label: "Profile", to: "/profile", icon: CircleUserRound },
    ].map((item) => <Link key={item.to} to={item.to} activeProps={{ className: "text-primary bg-accent" }} className="flex min-w-0 flex-col items-center gap-1 rounded-md px-1 py-2 text-[10px] font-bold text-muted-foreground"><item.icon className="size-5" /><span className="truncate">{item.label}</span></Link>)}</nav>
  </div>;
}

function StatusBadge({ status }: { status: Status | string }) {
  const style = status === "Present" || status === "Approved" || status === "Active" ? "bg-success-soft text-success" : status === "Late" || status === "Pending" || status === "Half Day" ? "bg-warning-soft text-warning" : status === "Absent" || status === "Rejected" || status === "Inactive" ? "bg-danger-soft text-destructive" : "bg-info-soft text-primary";
  return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold", style)}>{status}</span>;
}

function StatCard({ label, value, detail, icon: Icon, tone = "primary" }: { label: string; value: string; detail: string; icon: typeof Clock3; tone?: "primary" | "success" | "warning" | "danger" }) {
  const tones = { primary: "bg-info-soft text-primary", success: "bg-success-soft text-success", warning: "bg-warning-soft text-warning", danger: "bg-danger-soft text-destructive" };
  return <div className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p></div><div className={cn("grid size-10 place-items-center rounded-md", tones[tone])}><Icon className="size-5" /></div></div><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>;
}

function Section({ title, subtitle, action, children }: { title: string; subtitle?: string; action?: ReactNode; children: ReactNode }) {
  return <section className="rounded-lg border bg-card shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b px-4 py-4 md:px-5"><div className="min-w-0"><h2 className="truncate font-extrabold">{title}</h2>{subtitle && <p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>;
}

function DataTable({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="bg-muted/70">{headers.map((h) => <th key={h} className="px-5 py-3 text-xs font-bold uppercase text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-t transition-colors hover:bg-muted/35">{row.map((cell, j) => <td key={j} className="px-5 py-3.5">{cell}</td>)}</tr>)}</tbody></table></div>;
}

function EmptyState({ title, text }: { title: string; text: string }) { return <div className="grid min-h-52 place-items-center p-8 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-full bg-muted"><FileText className="size-5 text-muted-foreground" /></div><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{text}</p></div></div>; }

export function LoginPage() {
  const { role, setRole } = useDHA();
  const navigate = useNavigate();
  return <main className="grid min-h-screen lg:grid-cols-[minmax(340px,0.8fr)_1.2fr]">
    <section className="flex items-center justify-center bg-card px-5 py-10"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-md bg-primary text-xl font-extrabold text-primary-foreground">D</div><div><h1 className="text-xl font-extrabold">DHA Attendance</h1><p className="text-sm text-muted-foreground">Employee management portal</p></div></div><div><p className="text-sm font-bold text-primary">WELCOME BACK</p><h2 className="mt-2 text-3xl font-extrabold">Sign in to your workspace</h2><p className="mt-2 text-sm text-muted-foreground">Choose a demo role to explore the appropriate attendance tools.</p></div><div className="mt-8 space-y-4"><div><Label htmlFor="role">Demo access role</Label><select id="role" value={role} onChange={(e) => setRole(e.target.value as Role)} className="mt-2 h-11 w-full rounded-md border bg-background px-3 text-sm">{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><Button className="h-11 w-full" onClick={() => navigate({ to: "/dashboard" })}>Continue as {roleLabels[role]} <ChevronRight /></Button><p className="flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-success" /> Demo mode · No credentials required</p></div></div></section>
    <section className="relative hidden overflow-hidden bg-sidebar p-12 text-sidebar-foreground lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-x-0 top-0 h-1 bg-sidebar-primary" /><p className="text-sm font-bold text-sidebar-primary">DHA COMPANY · PEOPLE & CULTURE</p><div className="max-w-2xl"><p className="text-5xl font-extrabold leading-[1.1]">Every workday,<br />clearly accounted for.</p><p className="mt-5 max-w-lg text-lg text-sidebar-foreground/65">A focused workspace for attendance, leave planning, approvals and workforce reporting.</p><div className="mt-10 grid grid-cols-3 gap-4"><div className="border-l-2 border-sidebar-primary pl-4"><p className="text-3xl font-extrabold">94.2%</p><p className="text-sm text-sidebar-foreground/55">Attendance rate</p></div><div className="border-l-2 border-sidebar-primary pl-4"><p className="text-3xl font-extrabold">148</p><p className="text-sm text-sidebar-foreground/55">Active employees</p></div><div className="border-l-2 border-sidebar-primary pl-4"><p className="text-3xl font-extrabold">3</p><p className="text-sm text-sidebar-foreground/55">Departments</p></div></div></div><p className="text-xs text-sidebar-foreground/40">Prototype data · Pakistan Standard Time</p></section>
  </main>;
}

export function DashboardPage() {
  const { role, checkedIn, checkedOut, checkIn, checkOut } = useDHA();
  const isAdmin = role === "hr_admin" || role === "system_admin";
  if (isAdmin) return <AppShell title="HR Overview" eyebrow="Company dashboard"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active employees" value="148" detail="3 joined this month" icon={Users} /><StatCard label="Present today" value="132" detail="89.2% of workforce" icon={CheckCircle2} tone="success" /><StatCard label="Late arrivals" value="9" detail="Down 3 from yesterday" icon={Timer} tone="warning" /><StatCard label="Pending actions" value="7" detail="4 leave · 3 corrections" icon={FileClock} tone="danger" /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Section title="Attendance by department" subtitle="Today's workforce status"><div className="space-y-5 p-5">{[["Operations",94, "63 / 67"],["Human Resources",88,"22 / 25"],["Finance",91,"51 / 56"]].map(([name, rate, count]) => <div key={name as string}><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{name}</span><span className="text-muted-foreground">{count} · {rate}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${rate}%` }} /></div></div>)}</div></Section><Section title="Needs attention" subtitle="Requests awaiting review" action={<Button asChild variant="ghost" size="sm"><Link to="/approvals">View all</Link></Button>}><div className="divide-y">{leaveRequests.slice(0,2).map((r) => <div key={r.id} className="flex items-center gap-3 p-4"><div className="grid size-9 place-items-center rounded-full bg-warning-soft text-warning"><Palmtree className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{r.employee}</p><p className="truncate text-xs text-muted-foreground">{r.type} · {r.dates}</p></div><StatusBadge status={r.status} /></div>)}</div></Section></div></AppShell>;
  if (role === "manager") return <AppShell title="Team Dashboard" eyebrow="Operations"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Team members" value="24" detail="Operations Department" icon={Users} /><StatCard label="Present" value="19" detail="79.2% of team" icon={CheckCircle2} tone="success" /><StatCard label="Late" value="3" detail="After 09:15 AM" icon={Timer} tone="warning" /><StatCard label="Away" value="2" detail="1 leave · 1 absent" icon={AlertCircle} tone="danger" /></div><div className="mt-5"><Section title="Today's team" subtitle="Live attendance snapshot" action={<Button asChild variant="outline" size="sm"><Link to="/team-attendance">Full team</Link></Button>}><DataTable headers={["Employee","Check in","Status"]} rows={team.map((m) => [<div><p className="font-bold">{m.name}</p><p className="text-xs text-muted-foreground">{m.code}</p></div>,m.checkIn,<StatusBadge status={m.status} />])} /></Section></div></AppShell>;
  return <AppShell title="Good afternoon, Hamza" eyebrow="Employee dashboard"><div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><section className="rounded-lg bg-sidebar p-6 text-sidebar-foreground shadow-sm"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-start"><div><p className="text-sm font-bold text-sidebar-primary">TODAY · GENERAL SHIFT</p><p className="mt-2 text-3xl font-extrabold">{checkedOut ? "Workday complete" : checkedIn ? "You're checked in" : "Ready to start?"}</p><p className="mt-2 text-sidebar-foreground/60">09:00 AM – 05:30 PM · 15 min grace</p></div><div className="rounded-md bg-sidebar-accent p-4 text-center"><p className="text-xs text-sidebar-foreground/60">Current status</p><p className="mt-1 font-extrabold text-sidebar-primary">{checkedOut ? "COMPLETED" : checkedIn ? "PRESENT" : "NOT CHECKED IN"}</p></div></div><div className="mt-8 flex flex-wrap gap-3">{!checkedIn ? <Button onClick={checkIn} className="min-w-40 bg-sidebar-primary text-sidebar-primary-foreground hover:bg-sidebar-primary/90"><Clock3 /> Check in now</Button> : <Button onClick={checkOut} disabled={checkedOut} className="min-w-40 bg-sidebar-primary text-sidebar-primary-foreground hover:bg-sidebar-primary/90"><LogOut /> {checkedOut ? "Checked out" : "Check out"}</Button>}<Button asChild variant="outline" className="border-sidebar-border bg-sidebar/20 text-sidebar-foreground hover:bg-sidebar-accent"><Link to="/attendance">View attendance</Link></Button></div></section><Section title="Leave balance" subtitle="2026 allocation"><div className="grid grid-cols-3 divide-x p-5 text-center"><div><p className="text-2xl font-extrabold">12</p><p className="text-xs text-muted-foreground">Annual</p></div><div><p className="text-2xl font-extrabold">7</p><p className="text-xs text-muted-foreground">Sick</p></div><div><p className="text-2xl font-extrabold">3</p><p className="text-xs text-muted-foreground">Casual</p></div></div></Section></div><div className="mt-5"><Section title="Recent attendance" action={<Button asChild variant="ghost" size="sm"><Link to="/attendance">View all</Link></Button>}><DataTable headers={["Date","Check in","Check out","Hours","Status"]} rows={attendance.slice(0,5).map((a) => [<div><p className="font-bold">{a.date}</p><p className="text-xs text-muted-foreground">{a.day}</p></div>,a.checkIn,a.checkOut,a.hours,<StatusBadge status={a.status} />])} /></Section></div></AppShell>;
}

function CorrectionDialog() {
  const [error, setError] = useState("");
  const [open, setOpen] = useState(false);
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const result = z.object({ reason: z.string().trim().min(10, "Please provide at least 10 characters.").max(300) }).safeParse({ reason: data.get("reason") }); if (!result.success) { setError(result.error.issues[0]?.message ?? "Please check the form."); return; } setError(""); setOpen(false); toast.success("Correction request submitted", { description: "Your manager has been notified." }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Pencil /> Request correction</Button></DialogTrigger><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>Request attendance correction</DialogTitle><DialogDescription>Update the missed times for 24 September. Your manager will review the request.</DialogDescription></DialogHeader><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="cin">Check-in</Label><Input id="cin" type="time" defaultValue="09:00" className="mt-2" /></div><div><Label htmlFor="cout">Check-out</Label><Input id="cout" type="time" defaultValue="17:30" className="mt-2" /></div><div className="sm:col-span-2"><Label htmlFor="reason">Reason</Label><Textarea id="reason" name="reason" className="mt-2" placeholder="Explain why this record needs correction" maxLength={300} />{error && <p className="mt-2 flex items-center gap-1 text-xs font-semibold text-destructive"><AlertCircle className="size-3" />{error}</p>}</div></div><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Submit request</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function AttendancePage() {
  const [status, setStatus] = useState("all");
  const filtered = status === "all" ? attendance : attendance.filter((a) => a.status === status);
  return <AppShell title="My Attendance" eyebrow="Personal records" actions={<CorrectionDialog />}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Present" value="18" detail="Working days this month" icon={CheckCircle2} tone="success" /><StatCard label="Late" value="2" detail="On-time rate 90%" icon={Timer} tone="warning" /><StatCard label="Absent" value="1" detail="Unexcused absence" icon={XCircle} tone="danger" /><StatCard label="Worked hours" value="154h" detail="8h 7m daily average" icon={Clock3} /></div><div className="mt-5"><Section title="September 2026" subtitle="Monthly attendance register" action={<div className="flex gap-2"><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter by status" className="h-9 rounded-md border bg-background px-3 text-sm"><option value="all">All statuses</option>{["Present","Late","Absent","On Leave","Holiday","Half Day"].map((s) => <option key={s}>{s}</option>)}</select></div>}><DataTable headers={["Date","Check in","Check out","Worked","Status"]} rows={filtered.map((a) => [<div><p className="font-bold">{a.date}</p><p className="text-xs text-muted-foreground">{a.day}</p></div>,a.checkIn,a.checkOut,a.hours,<StatusBadge status={a.status} />])} /></Section></div></AppShell>;
}

function LeaveDialog() {
  const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const d = new FormData(e.currentTarget); const result = z.object({ start: z.string().min(1), end: z.string().min(1), reason: z.string().trim().min(10, "Please explain your request in at least 10 characters.").max(500) }).safeParse({ start: d.get("start"), end: d.get("end"), reason: d.get("reason") }); if (!result.success) { setError(result.error.issues[0]?.message ?? "Complete all fields."); return; } if (String(d.get("start")) > String(d.get("end"))) { setError("End date must be after the start date."); return; } setError(""); setOpen(false); toast.success("Leave request submitted", { description: "Your manager will review it shortly." }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus /> New leave request</Button></DialogTrigger><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>New leave request</DialogTitle><DialogDescription>Your available annual balance is 12 days.</DialogDescription></DialogHeader><div className="mt-5 space-y-4"><div><Label>Leave type</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm"><option>Annual Leave</option><option>Sick Leave</option><option>Casual Leave</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="start">Start date</Label><Input id="start" name="start" type="date" className="mt-2" /></div><div><Label htmlFor="end">End date</Label><Input id="end" name="end" type="date" className="mt-2" /></div></div><div><Label htmlFor="leave-reason">Reason</Label><Textarea id="leave-reason" name="reason" maxLength={500} className="mt-2" placeholder="Reason for leave" /></div>{error && <p className="flex items-center gap-2 rounded-md bg-danger-soft p-3 text-sm font-semibold text-destructive"><AlertCircle className="size-4" />{error}</p>}</div><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Submit request</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function LeavePage() { const [tab, setTab] = useState("requests"); return <AppShell title="Leave" eyebrow="Time away" actions={<LeaveDialog />}><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Annual leave" value="12 days" detail="8 of 20 used" icon={Palmtree} /><StatCard label="Sick leave" value="7 days" detail="3 of 10 used" icon={Activity} tone="success" /><StatCard label="Casual leave" value="3 days" detail="2 of 5 used" icon={CalendarDays} tone="warning" /></div><div className="mt-5"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="requests">My requests</TabsTrigger><TabsTrigger value="policy">Leave policy</TabsTrigger></TabsList><TabsContent value="requests" className="mt-4"><Section title="Request history" subtitle="Track current and previous requests"><DataTable headers={["Type","Dates","Days","Reason","Status"]} rows={leaveRequests.filter((r) => r.employee === "Hamza Khan").map((r) => [<span className="font-bold">{r.type}</span>,r.dates,r.days,r.reason,<StatusBadge status={r.status} />])} /></Section></TabsContent><TabsContent value="policy" className="mt-4"><Section title="2026 leave policy"><div className="grid gap-4 p-5 md:grid-cols-3">{[["Annual Leave","20 days","Planned time away; submit at least 3 days in advance."],["Sick Leave","10 days","Medical documentation may be requested after 2 days."],["Casual Leave","5 days","For urgent personal matters and short absences."]].map(([name,days,text]) => <div key={name} className="border-l-2 border-primary pl-4"><p className="font-bold">{name}</p><p className="mt-1 text-sm font-semibold text-primary">{days}</p><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div></Section></TabsContent></Tabs></div></AppShell>; }

export function TeamAttendancePage() { const [query, setQuery] = useState(""); const filtered = team.filter((m) => m.name.toLowerCase().includes(query.toLowerCase())); return <AppShell title="Team Attendance" eyebrow="Operations"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Present" value="19" detail="79.2% of team" icon={CheckCircle2} tone="success" /><StatCard label="Late" value="3" detail="12.5% of team" icon={Timer} tone="warning" /><StatCard label="On leave" value="1" detail="Approved leave" icon={Palmtree} /><StatCard label="Absent" value="1" detail="Needs follow-up" icon={XCircle} tone="danger" /></div><div className="mt-5"><Section title="Today's register" subtitle="29 September 2026" action={<div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search team" className="w-48 pl-9" /></div>}>{filtered.length ? <DataTable headers={["Employee","Department","Check in","Status","Action"]} rows={filtered.map((m) => [<div><p className="font-bold">{m.name}</p><p className="text-xs text-muted-foreground">{m.code}</p></div>,m.department,m.checkIn,<StatusBadge status={m.status} />,<Button variant="ghost" size="icon" aria-label={`Actions for ${m.name}`}><MoreHorizontal /></Button>])} /> : <EmptyState title="No team members found" text="Try a different employee name." />}</Section></div></AppShell>; }

export function ApprovalsPage() { const [requests, setRequests] = useState(leaveRequests.filter((r) => r.status === "Pending")); const decide = (id: number, choice: "Approved" | "Rejected") => { setRequests((all) => all.filter((r) => r.id !== id)); toast.success(`Request ${choice.toLowerCase()}`, { description: "The employee has been notified." }); }; return <AppShell title="Approvals" eyebrow="Manager workspace"><Tabs defaultValue="leave"><TabsList><TabsTrigger value="leave">Leave requests ({requests.length})</TabsTrigger><TabsTrigger value="corrections">Corrections (2)</TabsTrigger></TabsList><TabsContent value="leave" className="mt-4"><Section title="Pending leave requests" subtitle="Review team requests">{requests.length ? <div className="divide-y">{requests.map((r) => <div key={r.id} className="grid gap-4 p-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold">{r.employee}</p><StatusBadge status="Pending" /></div><p className="mt-1 text-sm text-muted-foreground">{r.type} · {r.dates} · {r.days} days</p><p className="mt-3 text-sm">“{r.reason}”</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => decide(r.id,"Rejected")}><X /> Reject</Button><Button onClick={() => decide(r.id,"Approved")}><Check /> Approve</Button></div></div>)}</div> : <EmptyState title="All caught up" text="There are no leave requests waiting for review." />}</Section></TabsContent><TabsContent value="corrections" className="mt-4"><Section title="Attendance corrections"><DataTable headers={["Employee","Date","Requested time","Reason","Action"]} rows={[[<div><p className="font-bold">Hamza Khan</p><p className="text-xs text-muted-foreground">DHA-1042</p></div>,"24 Sep 2026","09:00 AM – 05:30 PM","System outage",<Button size="sm" onClick={() => toast.success("Correction approved")}>Review</Button>],[<div><p className="font-bold">Ali Hassan</p><p className="text-xs text-muted-foreground">DHA-1073</p></div>,"22 Sep 2026","09:05 AM – 05:40 PM","Missed check-out",<Button size="sm" onClick={() => toast.success("Correction approved")}>Review</Button>]]} /></Section></TabsContent></Tabs></AppShell>; }

export function EmployeesPage() { const [query,setQuery] = useState(""); const [list,setList] = useState(employees); const filtered=list.filter((e)=>`${e.name} ${e.code} ${e.department}`.toLowerCase().includes(query.toLowerCase())); const toggle=(code:string)=>setList((all)=>all.map((e)=>e.code===code?{...e,status:e.status==="Active"?"Inactive":"Active"}:e)); return <AppShell title="Employees" eyebrow="HR administration" actions={<Button onClick={()=>toast.success("Employee draft opened")}><Plus /> Add employee</Button>}><Section title="Employee directory" subtitle={`${list.filter((e)=>e.status==="Active").length} active employees in this demo`} action={<div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search employees" className="w-52 pl-9"/></div>}>{filtered.length?<DataTable headers={["Employee","Department","Designation","Shift","Status","Action"]} rows={filtered.map((e)=>[<div><p className="font-bold">{e.name}</p><p className="text-xs text-muted-foreground">{e.code}</p></div>,e.department,e.designation,e.shift,<StatusBadge status={e.status}/>,<Button variant="ghost" size="sm" onClick={()=>{toggle(e.code);toast.success(`${e.name} ${e.status==="Active"?"deactivated":"activated"}`)}}>{e.status==="Active"?"Deactivate":"Activate"}</Button>])}/>:<EmptyState title="No employees found" text="Try another name, code or department."/>}</Section></AppShell>; }

export function OrganizationPage() { return <AppShell title="Departments & Shifts" eyebrow="Organization setup"><Tabs defaultValue="departments"><TabsList><TabsTrigger value="departments">Departments</TabsTrigger><TabsTrigger value="shifts">Shifts</TabsTrigger></TabsList><TabsContent value="departments" className="mt-4"><Section title="Departments" action={<Button size="sm" onClick={()=>toast.success("Department form opened")}><Plus/> Add</Button>}><DataTable headers={["Department","Head","Employees","Attendance rate"]} rows={[["Operations","Sara Ali","67","94%"],["Human Resources","Ayesha Malik","25","88%"],["Finance","Farhan Sheikh","56","91%"]].map((r)=>[<span className="font-bold">{r[0]}</span>,...r.slice(1)])}/></Section></TabsContent><TabsContent value="shifts" className="mt-4"><Section title="Work shifts" action={<Button size="sm" onClick={()=>toast.success("Shift form opened")}><Plus/> Add</Button>}><DataTable headers={["Shift","Hours","Grace period","Working days"]} rows={[[<span className="font-bold">General</span>,"09:00 AM – 05:30 PM","15 minutes","Mon–Sat"],[<span className="font-bold">Early</span>,"08:00 AM – 04:30 PM","10 minutes","Mon–Sat"]]}/></Section></TabsContent></Tabs></AppShell>; }

export function LeaveHolidaysPage() { return <AppShell title="Leave & Holidays" eyebrow="Policy setup"><div className="grid gap-5 xl:grid-cols-2"><Section title="Leave types" action={<Button size="sm" onClick={()=>toast.success("Leave type form opened")}><Plus/> Add</Button>}><DataTable headers={["Type","Annual quota","Paid"]} rows={[["Annual Leave","20 days","Yes"],["Sick Leave","10 days","Yes"],["Casual Leave","5 days","Yes"]].map((r)=>[<span className="font-bold">{r[0]}</span>,r[1],<StatusBadge status={r[2]}/ >])}/></Section><Section title="Upcoming holidays" action={<Button size="sm" onClick={()=>toast.success("Holiday form opened")}><Plus/> Add</Button>}><div className="divide-y">{[["Iqbal Day","09 Nov 2026"],["Quaid-e-Azam Day","25 Dec 2026"],["Kashmir Day","05 Feb 2027"]].map(([name,date])=><div key={name} className="flex items-center justify-between p-4"><div><p className="font-bold">{name}</p><p className="text-xs text-muted-foreground">Public holiday</p></div><span className="text-sm font-semibold">{date}</span></div>)}</div></Section></div></AppShell>; }

export function ReportsPage() { const [generated,setGenerated]=useState(true); const rows=[["DHA-1042","Hamza Khan","Operations",18,2,1,1],["DHA-1017","Ayesha Malik","Human Resources",21,0,0,1],["DHA-1068","Bilal Ahmed","Finance",20,1,0,1],["DHA-1091","Sara Ali","Operations",19,0,0,2]]; const download=()=>{const csv="Code,Employee,Department,Present,Late,Absent,Leave\n"+rows.map((r)=>r.join(",")).join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="dha-attendance-september-2026.csv";a.click();URL.revokeObjectURL(a.href);toast.success("CSV report downloaded")}; return <AppShell title="Attendance Reports" eyebrow="Workforce insights" actions={<Button variant="outline" onClick={download} disabled={!generated}><Download/> Export CSV</Button>}><section className="rounded-lg border bg-card p-4 shadow-sm"><div className="grid gap-4 md:grid-cols-4"><div><Label>Month</Label><select className="mt-2 h-9 w-full rounded-md border bg-background px-3 text-sm"><option>September 2026</option><option>August 2026</option></select></div><div><Label>Department</Label><select className="mt-2 h-9 w-full rounded-md border bg-background px-3 text-sm"><option>All departments</option><option>Operations</option><option>Human Resources</option><option>Finance</option></select></div><div><Label>Status</Label><select className="mt-2 h-9 w-full rounded-md border bg-background px-3 text-sm"><option>All employees</option><option>Active only</option></select></div><div className="flex items-end"><Button className="w-full" onClick={()=>{setGenerated(true);toast.success("Report generated")}}><FileText/> Generate report</Button></div></div></section><div className="mt-5"><Section title="September attendance summary" subtitle="1–29 September 2026">{generated?<DataTable headers={["Employee","Department","Present","Late","Absent","Leave"]} rows={rows.map((r)=>[<div><p className="font-bold">{r[1]}</p><p className="text-xs text-muted-foreground">{r[0]}</p></div>,r[2],r[3],r[4],r[5],r[6]])}/>:<EmptyState title="Generate a report" text="Choose filters above to see attendance totals."/>}</Section></div></AppShell>; }

export function NotificationsPage() { const [items,setItems]=useState([{id:1,title:"Leave request approved",text:"Your casual leave for 21 September was approved.",time:"2 hours ago",read:false},{id:2,title:"Correction updated",text:"Your attendance record for 24 September was corrected.",time:"Yesterday",read:false},{id:3,title:"Upcoming holiday",text:"Iqbal Day is observed on 9 November.",time:"3 days ago",read:true}]); return <AppShell title="Notifications" eyebrow="Updates" actions={<Button variant="outline" onClick={()=>setItems(items.map((i)=>({...i,read:true})))}>Mark all read</Button>}><Section title="Recent notifications" subtitle={`${items.filter((i)=>!i.read).length} unread`}><div className="divide-y">{items.map((item)=><button key={item.id} onClick={()=>setItems(items.map((i)=>i.id===item.id?{...i,read:true}:i))} className="grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-3 p-5 text-left hover:bg-muted/40"><span className={cn("mt-1 size-2 rounded-full",item.read?"bg-muted":"bg-primary")}/><span className="min-w-0"><span className="block font-bold">{item.title}</span><span className="mt-1 block text-sm text-muted-foreground">{item.text}</span></span><span className="text-xs text-muted-foreground">{item.time}</span></button>)}</div></Section></AppShell>; }

export function UsersPage() { return <AppShell title="Users & Roles" eyebrow="System administration" actions={<Button onClick={()=>toast.success("User invitation draft opened")}><Plus/> Add user</Button>}><div className="mb-5 rounded-md border border-warning/30 bg-warning-soft p-4 text-sm"><p className="flex items-center gap-2 font-bold"><ShieldCheck className="size-4 text-warning"/> Role assignments</p><p className="mt-1 text-muted-foreground">This prototype only previews role changes. No real access permissions are changed.</p></div><Section title="User access" subtitle="5 demo accounts"><DataTable headers={["User","Role","Department","Status","Action"]} rows={employees.map((e,i)=>[<div><p className="font-bold">{e.name}</p><p className="text-xs text-muted-foreground">{e.code.toLowerCase()}@dha.demo</p></div>,<select className="h-8 rounded-md border bg-background px-2 text-xs" defaultValue={i===0?"employee":i===1?"hr_admin":"employee"} onChange={()=>toast.success("Role updated for this session")}><option value="employee">Employee</option><option value="manager">Manager</option><option value="hr_admin">HR Admin</option><option value="system_admin">System Admin</option></select>,e.department,<StatusBadge status={e.status}/>,<Button variant="ghost" size="icon" aria-label={`Settings for ${e.name}`}><Settings2/></Button>])}/></Section></AppShell>; }

export function AuditLogPage() { const [query,setQuery]=useState(""); const filtered=auditItems.filter((a)=>`${a.action} ${a.actor} ${a.target}`.toLowerCase().includes(query.toLowerCase())); return <AppShell title="Audit Log" eyebrow="Governance"><Section title="Activity history" subtitle="Administrative changes and approvals" action={<div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(e)=>setQuery(e.target.value)} className="w-52 pl-9" placeholder="Search activity"/></div>}>{filtered.length?<DataTable headers={["Action","Actor","Record","Time"]} rows={filtered.map((a)=>[<span className="font-bold">{a.action}</span>,a.actor,a.target,a.time])}/>:<EmptyState title="No activity found" text="Try a broader search term."/>}</Section></AppShell>; }

export function ProfilePage() { const {role}=useDHA(); return <AppShell title="My Profile" eyebrow="Personal details"><div className="grid gap-5 xl:grid-cols-[1fr_1.5fr]"><Section title="Employee card"><div className="p-6 text-center"><div className="mx-auto grid size-20 place-items-center rounded-full bg-primary text-2xl font-extrabold text-primary-foreground">HK</div><h2 className="mt-4 text-xl font-extrabold">Hamza Khan</h2><p className="text-sm text-muted-foreground">Operations Executive</p><div className="mt-4"><StatusBadge status={roleLabels[role]}/></div></div></Section><Section title="Work information" action={<Button size="sm" variant="outline" onClick={()=>toast.info("Profile editing is a demo action")}><Pencil/> Edit</Button>}><dl className="grid gap-5 p-5 sm:grid-cols-2">{[["Employee code","DHA-1042"],["Department","Operations"],["Manager","Sara Ali"],["Shift","General · 09:00–17:30"],["Phone","+92 300 555 0184"],["Join date","12 March 2023"]].map(([term,value])=><div key={term}><dt className="text-xs font-bold uppercase text-muted-foreground">{term}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></Section></div><div className="mt-5"><Section title="Account"><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">End demo session</p><p className="text-sm text-muted-foreground">Return to role selection. Temporary changes reset on refresh.</p></div><Button asChild variant="outline"><Link to="/"><LogOut/> Sign out</Link></Button></div></Section></div></AppShell>; }